### ISSUE TITLE
No locale found

### ISSUE THREAD

**Issue by Toonu** [dymanoid/RealTime#9] opened 2018-06-26 10:50 UTC
![screenshot](https://user-images.githubusercontent.com/4078304/41906937-a527c048-793f-11e8-8904-4fa1bbc75911.png)
Hello, I've added your mod and its working nicely, the only problem is that the settings for the mod is all showing No locale found, meaning I can't set up the values because I don't know what they mean. Or at least screenshot of the normal settings would be helpful for setup. 👍

**Comment by dymanoid** [comment] 2018-06-26 15:58
@Toonu, which game version do you have? Does it happen all the time, or the settings are OK after a game restart?

**Comment by DalveenLeandor** [comment] 2018-06-28 09:06
it happen to me 1 time, i change game language to English and return to my language and it solve.

**Comment by dymanoid** [comment] 2018-07-04 20:44
Still cannot reproduce the issue.

**Comment by Toonu** [comment] 2018-07-05 06:17
Maybe it's some other mod incompability?

**Comment by timapelov** [comment] 2018-07-19 09:55
I also had this bug, I changed the name of the mod folder to "RealTime" and everything became correct.

**Comment by dymanoid** [comment] 2018-07-19 18:36
@timapelov, please don't change the folder names because they are managed by Steam.

**Comment by Eragon2016** [comment] 2018-07-25 16:18
hey i have the same problem and i have tried changing the game language to a different language and then back to the language i use but it does not work even enabling one real time does not work

**Comment by dymanoid** [comment] 2018-07-25 17:35
@Eragon2016, please share your game's log file just after the issue occurs. Otherwise, I'm unable to tell what is wrong. I cannot reproduce this issue.

**Comment by Eragon2016** [comment] 2018-07-25 19:09
he 'Real Time' cannot load data from localization file 'C:\Users\ERAGON2016\AppData\Local\Colossal Order\Cities_Skylines\Addons\Mods\RealTime\Localization\en.xml', error message: System.Xml.XmlException: Text node cannot appear in this state. file:///C:/Users/ERAGON2016/AppData/Local/Colossal Order/Cities_Skylines/Addons/Mods/RealTime/Localization/en.xml Line 80, position 12.
  at Mono.Xml2.XmlTextReader.ReadText (Boolean notWhitespace) [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.ReadContent () [0x00000] in <filename unknown>:0 
  at Mono.Xml2.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlTextReader.Read () [0x00000] in <filename unknown>:0 
  at Mono.Xml.EntityResolvingXmlReader.Read () [0x00000] in <filename unknown>:0 
  at Mono.Xml.Schema.XsdValidatingReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlValidatingReader.Read () [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.ReadNodeCore (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.ReadNode (System.Xml.XmlReader reader) [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.Load (System.Xml.XmlReader xmlReader) [0x00000] in <filename unknown>:0 
  at System.Xml.XmlDocument.Load (System.String filename) [0x00000] in <filename unknown>:0 
  at RealTime.Localization.LocalizationProvider.Load (System.String language) [0x00000] in <filename unknown>:0 
is this it i'm new to this

**Comment by dymanoid** [comment] 2018-07-25 19:41
@Eragon2016, thank you for this valuable information. It seems to be an issue with the Unity3D game engine. I'll create a workaround for this.

**Comment by Eragon2016** [comment] 2018-07-25 19:43
thank you but i use the .xml that the mod created

**Comment by dymanoid** [comment] 2018-07-25 19:50
So you don't change anything in the XML files, right? Which language is this?

**Comment by Eragon2016** [comment] 2018-07-25 19:53
english no i don't only when i want to change a setting from the mod options then i do 
<?xml version="1.0" encoding="UTF-8"?>

-<RealTimeConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<Version>1</Version>

<WakeupHour>6</WakeupHour>

<GoToSleepUpHour>22</GoToSleepUpHour>

<IsDynamicDayLengthEnabled>true</IsDynamicDayLengthEnabled>

<DayTimeSpeed>5</DayTimeSpeed>

<NightTimeSpeed>5</NightTimeSpeed>

<VirtualCitizens>None</VirtualCitizens>

<IsWeekendEnabled>true</IsWeekendEnabled>

<IsLunchtimeEnabled>true</IsLunchtimeEnabled>

<StopConstructionAtNight>false</StopConstructionAtNight>

<ConstructionSpeed>100</ConstructionSpeed>

<SwitchOffLightsAtNight>true</SwitchOffLightsAtNight>

<SecondShiftQuota>12</SecondShiftQuota>

<NightShiftQuota>6</NightShiftQuota>

<LunchQuota>80</LunchQuota>

<LocalBuildingSearchQuota>60</LocalBuildingSearchQuota>

<OnTimeQuota>80</OnTimeQuota>

<AreEventsEnabled>true</AreEventsEnabled>

<EarliestHourEventStartWeekday>16</EarliestHourEventStartWeekday>

<LatestHourEventStartWeekday>20</LatestHourEventStartWeekday>

<EarliestHourEventStartWeekend>8</EarliestHourEventStartWeekend>

<LatestHourEventStartWeekend>22</LatestHourEventStartWeekend>

<WorkBegin>9</WorkBegin>

<WorkEnd>18</WorkEnd>

<LunchBegin>12</LunchBegin>

<LunchEnd>14</LunchEnd>

<MaxOvertime>2</MaxOvertime>

<SchoolBegin>8</SchoolBegin>

<SchoolEnd>15</SchoolEnd>

</RealTimeConfig>
i change from here since is shows the names hope i'm not making a mistake

**Comment by Eragon2016** [comment] 2018-07-25 19:54
english and no i don't change anything

**Comment by Eragon2016** [comment] 2018-07-28 14:48
thank you for trying to fix it but the problem is still there

**Comment by dymanoid** [comment] 2018-07-28 15:02
@Eragon2016, can you provide the log file please?

**Comment by Eragon2016** [comment] 2018-07-28 15:08
The 'Real Time' mod cannot find a required localization file 'C:\Program Files (x86)\Cities Skylines Parklife\Localization\en.xml'
there is this and everytime i open the gamei get a debug of all my mods but they work fine real time is my concern since i don't understand why it is this mod only and traffic manager

**Comment by aubergine10** [comment] 2018-07-28 15:37
How do you launch the game? Through Steam or a desktop shortcut? And do you install the mod via Steam Workshop or some manual method?

Likely source of issue is this function in [RealTimeMod.cs](https://github.com/dymanoid/RealTime/blob/master/src/RealTime/Core/RealTimeMod.cs):

```
        private static string GetModPath()
        {
            string assemblyName = typeof(RealTimeMod).Assembly.GetName().Name;

            PluginManager.PluginInfo pluginInfo = PluginManager.instance.GetPluginsInfo()
                .FirstOrDefault(pi => pi.name == assemblyName || pi.publishedFileID.AsUInt64 == WorkshopId);

            return pluginInfo == null
                ? Environment.CurrentDirectory
                : pluginInfo.modPath;
        }
```

Maybe `pluginInfo` is `null` and `Environment.CurrentDirectory` is returning wrong path? Either way, having some logging in `GetModPath()` function would help track down which value contains wrong path.

**Comment by dymanoid** [comment] 2018-07-28 15:53
Okay, so this is another issue, not the original one.

**Comment by dymanoid** [comment] 2018-07-28 15:55
BTW, the method you show has no issues. If there is no `PluginInfo` instance for the mod with a registered workshop ID in the game, then something is globally wrong.

**Comment by aubergine10** [comment] 2018-07-28 16:09
Yup, the game is doing something wrong, but which bit of the game? It would still be useful to track down and report to Paradox/CO. Reasoning: If that method will be included in #84 (either as part of the shared infrastructure or in the mods that use that infrastructure) then this issue is going to recur.

**Comment by Eragon2016** [comment] 2018-07-28 20:30
well a friend gave me the game and i download the mods though a website and not steam and i use none of the mods you have shown when i enter the game a pop-up appears saying that no source files has not been found for almost all the mods but they still work fine its only real time that does not show the options only no locale found

**Comment by dymanoid** [comment] 2018-07-28 20:35
Okay. **Real Time** doesn't support running without Steam Workshop, sorry.

**Closed by dymanoid** 2018-07-28 20:35 UTC
Labels: cannot reproduce, in discussion, won't fix

**Comment by Eragon2016** [comment] 2018-07-29 12:08
oh ok thank you anyway for trying to fix
