### ISSUE TITLE
new real time update breaks the game.

### ISSUE THREAD

**Issue by Diodonea** [dymanoid/RealTime#223] opened 2019-05-31 15:15 UTC
with today's new update, my games have stopped working, not even loading a new game. I had to remove the mod to play.

**Comment by dymanoid** [comment] 2019-05-31 15:37
Are you sure this has something to do with **Real Time**? There is no single comment on the Workshop page about that. This update was tested and it works.

Maybe some other mod was updated and causes an issue or an incompatibility.

You don't provide the log file of the game, so unfortunately there is little I can do.

**Comment by Diodonea** [comment] 2019-05-31 16:21
Where do I get the log file? Anyway today we have updated 4 mods including yours.
-Match Day Stadium: Colossal Park Sports Precinct
-More Advanced Toolbar
-Improved Public Transport 2
-81 celds

**Comment by dymanoid** [comment] 2019-05-31 17:06
Please carefully read **Real Time**'s description on the Workshop page. You will find a link to a guide explaining how to get log files.

**Comment by Diodonea** [comment] 2019-05-31 20:22
Curiously, the game works again. I have only removed 81 cells, but I don't see why it has come into conflict. About the output_log file, it has a lot of text and I don't know what you need.

**Comment by dymanoid** [comment] 2019-05-31 20:24
Just upload the whole file, you don't have to investigate it by yourself.

**Comment by Diodonea** [comment] 2019-05-31 20:25
[output_log.txt](https://github.com/dymanoid/RealTime/files/3242773/output_log.txt)

**Comment by dymanoid** [comment] 2019-05-31 20:35
Thanks for providing the log file.

There is nothing wrong about **Real Time** in your log file. You have some broken assets, the RICO mod causes a lot of errors, some system file cannot be found etc. Seems like your game installation is broken and there are too many bad assets. Try verifying your game installation and maybe unsubscribe from the assets that cause errors in the log file.

I'm closing this issue because it's not caused by **Real Time**.

**Closed** 2019-05-31 20:35 UTC
Labels: not an issue

**Comment by Diodonea** [comment] 2019-05-31 20:40
Thanks for the help. Is there any way to find out what assets are broken?

**Comment by dymanoid** [comment] 2019-05-31 21:01
Unfortunately it's not clear from the log file. There are really too many errors there.
E.g. this message tells that an asset is broken but doesn't tell which one:

`Trying to copy properties from null material.`

This one describes an error with the asset with Workshop ID 1092788151.

`Error with BUILDING_TITLE[1092788151.[tga] Entrance for S175AP2_Data]:0`

There are many similar error messages like above.

Also, there is some issue with the ' AutoSave` file.

Maybe you could re-verify your game installation first and then unsubscribe and re-subscribe all mods and assets,

**Comment by Diodonea** [comment] 2019-05-31 21:06
I will follow your advice, delete the game and do a complete cleaning of all the mods. it can't be that every time you load a game you throw 15 minutes loading. xD thank you very much again ;)
