### ISSUE TITLE
Livestock disappears when Real Time is turned on and reappears when turned off

### ISSUE THREAD

**Issue by TCapp40** [dymanoid/RealTime#191] opened 2018-11-15 20:57 UTC
Created a industrial farm - there were no animals in the pens although I was producing animal products, turned off real time mod and animals appeared, turned back on an animals disappeared.

**Comment by TCapp40** [comment] 2018-11-15 20:59
Tried using the real time mod and even though I was prducing animal products there were no animals in the pens, turned offreal time and they appeared
[debug.log](https://github.com/dymanoid/RealTime/files/2587015/debug.log)

**Comment by TCapp40** [comment] 2018-11-15 21:01
Created a industrial farm - there were no animals in the pens although I was producing animal products, turned off real time mod and animals appeared, tunred back on an animals disappeared.

**Comment by aubergine10** [comment] 2018-11-20 13:42
What time of day was it? In RT, farming industry is shut down at night and that likely causes farms to hide their animals.

@dymanoid : Is there a way to retain the animals in farms (both for older industry zones and newer industry areas) at night?

**Comment by TCapp40** [comment] 2018-11-20 15:38
It was day time

**Comment by dymanoid** [comment] 2018-11-20 20:19
> **@dymanoid** : Is there a way to retain the animals in farms (both for older industry zones and newer industry areas) at night?

Currently only by disabling the "switch lights at night" option.

**Comment by dymanoid** [comment] 2019-02-10 11:23
@TCapp40, could you please provide some screenshots for this issue?

**Comment by TCapp40** [comment] 2019-02-10 15:41
This happened months ago. I don’t use thevtealtine mod anymore I’m not sure I even have it in my assets.

**Comment by dymanoid** [comment] 2019-02-10 16:19
Okay. Since I cannot reproduce the issue anyway, I'm closing it.

**Closed by dymanoid** 2019-02-10 16:19 UTC
Labels: cannot reproduce

**Comment by TCapp40** [comment] 2019-02-10 17:29
Sounds good I had a few other mods going at the same time too so it could have been a combination of all the mods that were on.
