### ISSUE TITLE
University bug

### ISSUE THREAD

**Issue by DJSADERS** [dymanoid/RealTime#195] opened 2019-01-01 13:00 UTC
I've got an issue with universities, where 0 of my citizens are going as per the stats, however when it opens it fills up to maximum...

For example: 4039 uni spaces, 0 being used.
However when it opens at 8am 4039 citizens try to go even though 0 are supposed to be going as per the stats, but I get the not enough high educated citizens message.

**Comment by dymanoid** [comment] 2019-02-10 10:53
@DJSADERS, unfortunately, I cannot reproduce this issue as you describe it.
**Real Time** doesn't change the game's behavior that decides *which* citizens go to the university. **Real Time** only changes *how long* does it take to get an education level.
Please provide screenshots or even better a saved game where this issue can be observed.

**Comment by dymanoid** [comment] 2019-03-15 23:51
@DJSADERS, any news about this one?

**Comment by Asadlerpwcom** [comment] 2019-03-20 09:32
i'm still having issues, with the universities, but haven't had time to have a proper session on the game to see how bad it gets.

I'm still getting the full amount of students attending the university however the number of city students is significantly lower, and i am having issues with the amount of ambulances attending the university.
I had nearly 40 attending at one time, for no reason that i could see

**Comment by dymanoid** [comment] 2019-05-18 10:44
@Asadlerpwcom, the ambulances issue just cannot be caused by Real Time because this mod doesn't manage any city service or transportation.

**Comment by dymanoid** [comment] 2019-05-31 22:27
Since the OP is not responding, I'm closing this issue as not reproducible.

**Closed by dymanoid** 2019-05-31 22:27 UTC
Labels: cannot reproduce
