### ISSUE TITLE
Gets super busy at midnight for some reason continued

### ISSUE THREAD

**Issue by WatchfulRelic91** [dymanoid/RealTime#273] opened 2020-04-06 16:45 UTC
This is a continuation of this thread https://github.com/dymanoid/RealTime/issues/262 , which was not solved and received no feedback after the most recent comment. Re-posting is the only way i could see to get my issue solved.

I've been snooping around during the midnight rush, and it seems that a lot of these people are not industrial workers, and many are unemployed. They just go from shop to shop, then home after the rush is over, doesn't seem to have much to do with shopping after work. Still no clue what's going on. I also found another thread about the same thing here #174 at the end of it you say that you are fixing the issue. It seems that his problems are the same as mine, so i'm curious as to what the issue was and what the fix was. If it was a bug, maybe it's back after the sunset harbor update because i don't remember having this issue at all before the update.

**Comment by dymanoid** [comment] 2020-04-06 17:16
Closed as duplicate of #262.
Please don't post duplicated issues.

**Closed by dymanoid** 2020-04-06 17:16 UTC
Labels: duplicate
