### ISSUE TITLE
Link rate of PT boarding time to game speed

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#241] opened 2019-11-16 08:55 UTC
Regardless of game speed, the PT vehicles always allocate same amount of boarding time.

Would be great if they could spend longer boarding if the game speed is slower, maybe up to 30 seconds on game speed 1?

**Comment by DaEgi01** [comment] 2019-11-16 11:46
Boarding times are actually not a fixed time interval, but just how long it takes for cims to get in.
That is also the reason, why Realistic Walking Speed increases the boarding times so dramatically. I played around with the idea of making a dedicated mod that puts boarding on a fixed interval to fix the issue with RWS.

**Comment by dymanoid** [comment] 2019-11-18 20:33
Yes, the boarding time depends on the movement speed of the citizens, not on the time simulation speed. I think there is little Real Time could do - the game waits until all citizens "in fact" board the vehicle. We could teleport them or force to wait more at a stop, but that would be not a great feature IMHO.

**Comment by dymanoid** [comment] 2019-11-27 22:22
I'm closing this one because the "issue" is caused by the citizens movement speed which won't be affected by Real Time.

**Closed by dymanoid** 2019-11-27 22:22 UTC
Labels: won't fix
