### ISSUE TITLE
Looks like Harmony 2 breaking some patches

### ISSUE THREAD

**Issue by aubergine10** [dymanoid/RealTime#274] opened 2020-04-25 10:35 UTC
EDIT: Probably related to #264 ?

Noticed this in one of the support forums:

```diff
+ The 'Real Time' mod starts, game mode LoadGame.
 
+ The 'Real Time' mod will not change the citizens aging because a 'Lifecycle Rebalance' mod is active.
 
- Attempting to patch non-declared member virtual System.Boolean HumanAI::ArriveAtTarget(System.UInt16 instanceID, CitizenInstance& citizenData) (forbidden in Harmony 2.x)! Getting closest declared member for backwards compatibility...
 
- Attempting to patch non-declared member System.Boolean HumanAI::StartMoving(System.UInt32 citizenID, Citizen& data, System.UInt16 sourceBuilding, System.UInt16 targetBuilding) (forbidden in Harmony 2.x)! Getting closest declared member for backwards compatibility...
 
+ 23 Harmony method patches with ID 'com.cities_skylines.dymanoid.realtime' successfully applied.
```

[rt_output_log.txt](https://github.com/dymanoid/RealTime/files/4532787/rt_output_log.txt)

**Comment by dymanoid** [comment] 2020-05-22 23:02
This is a duplicate of #264.

**Closed by dymanoid** 2020-05-22 23:02 UTC
Labels: duplicate
