### ISSUE TITLE
Seems like something is wrong with the schedules

### ISSUE THREAD

**Issue by Sipke82** [dymanoid/RealTime#174] opened 2018-09-04 08:22 UTC
After numerous reports of users complaining about the midnight rushhour i've been snooping on my people. I also have a heavy midnight rush hour. in an effort to limit it, I reduced nightshift and 2nd workshift to 1% (the lowest possible) but still its extremely busy around midnight. 
Daytimespeed = 3
Nighttimespeed = 4
Some strange things are observed when snooping around:

![image](https://user-images.githubusercontent.com/30873812/45019160-f11b9880-b02b-11e8-867d-82242529f7dd.png)
At home, but snooper says: now: Shopping…

![image](https://user-images.githubusercontent.com/30873812/45019229-1c05ec80-b02c-11e8-9754-a532c0edb6e6.png)
Now: go shopping. But driving to work...While it’s after 22:00 (which i gave defined as city goes to sleep)...

![image](https://user-images.githubusercontent.com/30873812/45019214-13adb180-b02c-11e8-8f38-57d26f3aff69.png)
Now: go home. But driving to work...While it’s after 22:00 (which i gave defined as city goes to sleep)...

![image](https://user-images.githubusercontent.com/30873812/45019185-009ae180-b02c-11e8-9897-5b8db46cd1cf.png)
Driving to work at 23:00…
![image](https://user-images.githubusercontent.com/30873812/45019198-085a8600-b02c-11e8-8fc3-ba6321cf1b0e.png)
Arrives at 23:34 for her first workshift.

![image](https://user-images.githubusercontent.com/30873812/45019493-be25d480-b02c-11e8-803b-f0930b60a3e2.png)
Driving home from his 1st workshift at 00:47
Later i took another look at Earl, Apparently he went to the Lion enclosure in the middle of the night, but now off to work:
![image](https://user-images.githubusercontent.com/30873812/45022116-af8eeb80-b033-11e8-9bcf-abfbec85d4ac.png)

**Comment by Sipke82** [comment] 2018-09-04 11:48
> Having "go shopping" scheduled while being at home is totally OK. I don't see any troubles here.

Shouldn't the activity be "At home"? I monitored for a few (realtimegame hours) she just stayed at home, while snooping says: **now**: go shopping

> Driving home from 1st work shift in the night could be OK if that citizen was in a traffic jam or just needs a lot of time to get home because of a long route.

That was not the case, ill try to get another case, if the behavior persists with the AdvancedAI and ParkingAI disabled, see below.

> Visiting the zoo early in the morning could be OK. The zoos will open at 5:30 a.m. or earlier. Or maybe you activated the "Night tours" policy for that zoo.

Didn't have night tours activated. Besides i don't think its really realistic to travel to the other side of the city in the middle of the night before works starts at 07:45 (in my city).

> The other screenshots show "looking for a parking spot". Maybe this breaks the schedules because of the TM:PE's parking AI. Can you try to activate pocket cars and deactivate the advanced parking AI and see if that helps?

I will let the game run without advanced AI and Parking AI, will report later..

**Comment by dymanoid** [comment] 2018-09-04 12:13
> Shouldn't the activity be "At home"?

Why? This is not **Snooper**'s info by the way. This is the **Real Time**'s schedule info. It doesn't tell what the citizen _is doing now_ but rather what is _on the schedule now_. You can observe "go shopping" on the schedule for several hours while the citizen is at home: at night, most citizens prefer going to local shops. If there are none available or all of them are already full, the citizen will stay at home with scheduled shopping.

**Comment by Sipke82** [comment] 2018-09-04 12:35
okay... i was thinking that "now"is suggesting what is happening now, instead of whats happening "next". Would changing the word to "next" make sense?

On regard of the experiment without AdvancedAI/ParkingAI, can i enable despawning?
Or limit the experiment to disabling Parking AI.....

Because now without Advanced AI my city gridlocks =)

**Comment by Sipke82** [comment] 2018-09-04 14:57
AdvancedAI off
ParkingAI off
Despanwning On (sorry my city was not build with vanilla AI in mind)

23:00
![image](https://user-images.githubusercontent.com/30873812/45036835-cf3b0980-b05d-11e8-9129-2a69823058a9.png)
now: shopping, but actually going to work (this is an Office building)

![image](https://user-images.githubusercontent.com/30873812/45037475-5f2d8300-b05f-11e8-8143-e3eafdb99340.png)
Another one, while the next scheduled event is go home, amanda is driving to work, at 23.00

![image](https://user-images.githubusercontent.com/30873812/45037594-a3208800-b05f-11e8-83e8-b7dd0cd14769.png)
And another... (again to an Office)

![image](https://user-images.githubusercontent.com/30873812/45039027-e9c3b180-b062-11e8-9190-2ba7f1d4f022.png)
One more... she arrived at work @ 23:35, put her car in her pocket and became productive at the office.
![image](https://user-images.githubusercontent.com/30873812/45039204-62c30900-b063-11e8-9f5e-3e3975ba778d.png)

**Comment by dymanoid** [comment] 2018-09-04 17:16
- Citizen can go shopping and relaxing at any time, even at night (adults and young adults). This is not a bug. 
- Tourists leaving the city are OK.
- You have a 146k city, **Real Time** doesn't guarantee it will work perfectly with large cities. This will be solved with #165.

**Comment by Sipke82** [comment] 2018-09-04 19:58
So I've accumulated some data, starting at Wednesday:
![image](https://user-images.githubusercontent.com/30873812/45054217-9f572a80-b08c-11e8-9072-767651ffaf76.png)
The thing that people are reporting is the third "rush hour" peak. in my case it's the most brutal one!
Day speed 3
night speed 4
work start time : 7.45
work end time: 16:45
city wake time: 6:00
city sleep time: 22:00
Citizens simulation: like Vanilla

This was  data was taken with  TMPE enabled but Advanced AI and Parking AI disabled. Despawning enabled.
I observed a similar pattern when Advanced AI and Parking AI enabled and despawning disabled.

indeed i have a 150k city but with exception of the 22:00 rush hour i do not yet reach the vehicle/cim limit

**Comment by dymanoid** [comment] 2018-09-05 14:17
I think, the third rush hour is caused by the following reasons:

- the sleep time begins: **all** teens and children move home if they are somewhere else
- **almost all** tourists start moving to the hotels or leaving the city
- general traffic
- lots of delayed transfers due to the limited instances count

Can you check if you observe the same with a 40k city?

**Comment by Sipke82** [comment] 2018-09-05 20:51
So i loaded an older version of my city, 43 k people. First i let it ran for one realtime day, to equilibrate to current realtime version. Then i started the measurements again:
Day speed 3
night speed 4
work start time : 7.45
work end time: 16:45
city wake time: 6:00
city sleep time: 22:00
Citizens simulation: like Vanilla

![image](https://user-images.githubusercontent.com/30873812/45120262-e4975d00-b15d-11e8-9a92-2e1f72d00537.png)

Also for a small city (~43k) the phenomenon occurs. I still think some buggy behavior is taking place here as during the third rush hour (~23:00) a lot of people of going to their first work shift and a lot of people going to school. In addition it seems that the morning rush hour is a bit quiet, perhaps a lot of people already took the previous third rush hour to work?

Also, considering your feedback on what is allowed and expected by the current schedules, I think it could be made a bit more realistic. I have no idea about the technical possibilities and limitations. Before i make my proposal, my assumptions are:
There is a weekday schedule and a separate weekend schedule
Probabilities can be defined

Proposal Weekdays:
New CIM activity “Sleep”
If employed or student, the next activity after “sleep”is always “Work/Study”
After work/school, cims can go relaxing or shopping, but will go heading home to be at home at city sleep time (22:00). Thus not starting their journey at 22:00. But try to be at home at 22:00 just as with the work start time. Once at home, their activity will be “sleep”. Perhaps we can allow a small fraction (5%?) to deviate from this pattern?
Also uneducated cims will follow this goto home, as shops etc will be closed anyways. Perhaps we can allow a small fraction (5%?) to deviate from this pattern?

Proposal Weekends:
Define weekend start as friday after work endtime (default: 18:00)
Define the end of the weekend on sunday, again at work endtime (default 18:00)
Weekend during daytime, higher probability of shopping/park visit.
Weekend during after work endtime (default 18:00), increased leisure visit. Then after city sleep time (22:00?) slowly increase the probability to go home to 95% over a course of 2 hours?

With this setup i think it would be possible to have relative quiet weekday nights, because people need to go to work the next day. While the weekend nights (friday and saturday night) are busy clubbing nights.

**Comment by dymanoid** [comment] 2018-09-06 07:12
That is really strange. I cannot find an explanation for this "third rush hour", neither can I reproduce this with my local test cities. Maybe this is caused by some unfortunate mod combination or city layout.

Can you share your 43k city maybe?

**Comment by Sipke82** [comment] 2018-09-06 12:52
Well, i'm not the only one who sees this behavior, there are some reports in the workshop comments as well. For me this started around the time schedules were introduced. When i'll get home i'll share my save game with you.

I am using some mods though, perhaps District Service limit 3.0 is suspected, however I'm only using that mod to control the garbage trucks/hearses/ambulances/police cars. 

Perhaps you see another suspected mod on this list?

1. Speed Slider [v2]
2. Tree Movement Control
3. Tree LOD Fix
4. Remove Decoration Sprites   ("Grass" and "Rocks")
5. Emergency Lights Manager
6. District Service Limit 3.0
7. No Fires
8. Advanced Toolbar
9. Force Level Up
10. No Abandonment
11. Ultimate Eyecandy v1.5.2
12. Additive Shader
13. Building Eyedropper Tool
14. Decal Prop Fix
15. Theme Decals
16. Spawn/Unspawn Positions Swapper
17. Plop the Growables
18. Real Time
19. Customize It!
20. Parallel Road Tool
21. Traffic Manager: President Edition
22. Painter
23. Tree Brush
24. Ploppable RICO - High Density Fix
25. Procedural Objects
26. Snooper
27. Touch This! Tool 2.0.1
28. Unlimited Outside Connections (Beta)
29. Transparent Selectors
30. Airport Roads
31. Softer Shadows
32. PropRotating Params
33. Camera Positions Utility
34. First Person Camera: Updated
35. Metro Overhaul Mod
36. Train & Train Stations Converter -   read description!
37. Spawn Points Fix
38. Stats
39. Tree Fire Control
40. Realistic Walking Speed
41. Quay Anarchy
42. Advanced Stop Selection (ex MTSE)
43. Parkify
44. Building Themes (Green Cities)
45. Environment Changer (+ Improved Theme   Selection )
46. Improved Public Transport 2
47. Klyte Commons
48. Prop Line Tool [PLT] (vAlpha)
49. Zoning toolset (toggle + upgrade tool)
50. Network Tiling
51. Find It!
52. Unlock All + Wonders & Landmarks
53. CSL Show More Limits
54. Prop Precision
55. More Beautification
56. Ploppable Asphalt +
57. Prop & Tree Anarchy
58. Prop Snapping
59. Toggleable Whiteness
60. Random Tree Rotation
61. Network Skins (Park Life compatible)
62. Enhanced Mouse Light
63. Employment Details
64. One-Way Train Tracks
65. More Network Stuff
66. Prefab Hook (Mod Dependency)
67. Demand Master
68. Random Train Trailers 1.6.4
69. Sort Mod Settings
70. Network Extensions 2
71. Crossings
72. No Radioactive Desert And More!
73. No Seagulls
74. Loading Screen Mod
75. Fine Road Tool
76. 81 Tiles (Fixed for 1.2+)
77. Rail Track Speed Increaser 2.2.1
78. Fine Road Anarchy
79. Advanced Vehicle Options (AVO)
80. Sun Shafts
81. PostProcessFX v1.9.0
82. Relight
83. Dynamic Resolution (Fixed for 1.9!)
84. Dropouts
85. Surface Painter
86. Sharp Textures
87. Citizen Lifecycle Rebalance v2.3
88. Automatic Bulldoze v2
89. Automatic Emptying
90. Realistic Population and Consumption Mod   v8.3.3
91. Extra Landscaping Tools
92. Precision Engineering
93. Unlimited Trees Mod v1.10
94. Move It!
95. Traffic Report Mod: Updated

**Comment by dymanoid** [comment] 2018-09-06 15:42
Spotted the issue finally. Will be fixed ASAP.

**Closed** 2018-09-06 16:00 UTC
Labels: bug
