### ISSUE TITLE
Stadiums and Concerts events not working properly

### ISSUE THREAD

**Issue by Mazisky** [dymanoid/RealTime#202] opened 2019-03-06 11:25 UTC
When the event occours, almost no people go in compared to vanilla.

In vanilla, people start gathering to the event way before its start, and when the event begins there are almost 600\700 people in.

With Real time, only few people start going in, and when the event begins there are only 5\10 people (with a total of 700 capacity)
UPDATE: read next post

**Comment by Mazisky** [comment] 2019-03-15 11:02
So, i've tried to analyze that behaviour and i noticed that when people start gathering on the DLC events, the number doesn't raise because half of them are costantly leaving the place (concert or stadium), so the counter flicker up and down. 
So the problem is different,  **they go to the event, but then they go away.**

**Comment by dymanoid** [comment] 2019-03-15 19:14
This should not happen. Actually, this might be caused by an incompatible mod.

Inspect some citizens that are attending an event - e.g. a concert. What schedule status do you see?
Inspect some citizens that are heading to an event - what schedule status do they show? Continue watching citizens while they are attending an event. If a citizen leaves an event while the event is ongoing - what schedule status do you see for that citizen?

**Comment by Mazisky** [comment] 2019-03-15 20:00
I am trying now.

People going in "going to Concert area" without any other info.
People in there "visiting Concert area" without any other info.
People leaving "go home, go shopping, basically any possible destination".

I've noticed 2 things, they seem to act the same as they are visiting a park (i followed random people on parks to confront and they have the same behaviour)

some of them get "disoriented" while in the place.

I have only cosmetics mods at the moment "post processing fx", a lut, and ambient sound tuner.

**Comment by dymanoid** [comment] 2019-03-15 20:55
The citizens attending an event should show "relaxing" as their status and also the time they want to stay until. That time is the event closing time. The citizens should actually stay there until that time.

See the screenshot below:

![Cities Skylines Screenshot](https://user-images.githubusercontent.com/9433345/54461337-96968e00-476c-11e9-9ead-0a5676e3d144.png)

If it is not the case for your city, then something is generally wrong. Either there is some mod that prevents Real Time from working properly, or maybe you are using some old Real Time version.

**Comment by Mazisky** [comment] 2019-03-15 23:39
I've cleaned the APPdata folder to get rid of any possible leftover and now they seems to work properly!!!

Thank you very much for your help and time! much appreciated

**Comment by dymanoid** [comment] 2019-03-18 22:15
@Mazisky, I've just seen on Steam that other user have a similar issue. Could you please check whether the events still work for you? I suppose there was an update on some mod that now causes this issue. This has definitely worked in Real Time, and there were no recent updates of the mod. The game has not been updated for a while either.

**Comment by Mazisky** [comment] 2019-03-18 23:09
I've tried now and the concert got 150 people out of 300 so i think it should be ok.

When i had the issue only max 10 people were in because they were costantly leaving. 

Only Mod i used were
 
Realistic Population
Citizen lifecycle rebalance
Traffic Manager President
Realistic walking speed
Rebalanced industries.
Others were all graphics like postfrocessing FX or soften shadows so nothing that can interfere with the code.

Now i am using all of those minus traffic manager, maybe it is the guilty?

**Comment by Sipke82** [comment] 2019-05-10 20:42
I think i got the same problem, at my Stadium about 100 of 750 ppl are there at the start of the match.
It seems that a lot of people are joining the stadium as "shopping" and they leave quickly after they entered.
While also some people join as "relaxing till 20:30. and they seem to stay....

In addition, I noticed that almost nobody comes by car, instead 98% comes walking....

I do use a ton of other mods...

**Comment by RenaKunisaki** [comment] 2019-05-16 22:10
I've caught someone watching a concert with the status "working". Not sure if that's a bug, or they're just playing hooky. They did stick around for a while.

**Comment by Mazisky** [comment] 2019-05-17 07:28
After some tests i am pretty sure the mods who cause this problem is one of those 2:

Realistic population and consumption
Lifecycle rebalance.

One of these mess with Real time and causes this issue with events.

**Comment by dymanoid** [comment] 2019-05-18 10:41
@Mazisky, thanks for the hint! I will check it out. Maybe I find some workaround or contact that mod's author with a solution idea.

**Comment by RenaKunisaki** [comment] 2019-05-19 21:36
I'm not using either of those, but I am using some similar mods, maybe one of them is conflicting?

- Rebalanced Industries
- Cargo Hold Fix
- Rainfall (which pokes at quite a bit of code)
- Improved Public Transport 2
- Advanced Vehicle Options
- Metro Overhaul Mod (which I just installed today)

I just noticed today, a concert just plain didn't happen. The concerts and football matches have worked in the past but now it's showing a concert from 17:30 to 21:30 today, it's 18:15, the Festival Area is showing 0 visitors (even though I can see people in it), not showing any concert listed for today or currently happening, and indeed there's nobody on the stage.

The only other event-generating building I have, as far as I know, is the football stadium.

**Comment by dymanoid** [comment] 2019-05-28 15:03
@RenaKunisaki, this is a really strange one. According to the second screenshot, there is no concert at the stage. This can also explain why there are no visitors, only workers. However, Real Time shows an event on the time bar.

It looks like there is something that breaks the events, and this is not Real Time.

The events are displayed on the time bar when they are in a particular status (e.g. "preparing"). It seems like the concert is just stuck in that state, so it just didn't started. Real Time doesn't manage the vanilla game events (like concerts or football matches).

Maybe some mod is breaking them.

Could you maybe share your saved game?

**Comment by dymanoid** [comment] 2019-05-28 16:33
I tested with both mods enabled ("Realistic population and consumption" and "Citizen lifecycle rebalance") and unfortunately could not reproduce the issue.

**Comment by RenaKunisaki** [comment] 2019-05-28 18:54
I could share the savegame but unfortunately the city was wiped out by a gigantic tsunami... lol

I'll make sure to save a copy if it happens again.

**Comment by Sipke82** [comment] 2019-05-29 17:27
Could this be related to "realistic walking speed"... The cims just arrive too late?

**Comment by dymanoid** [comment] 2019-05-29 17:59
Yes, this could be the cause, indeed. Real Time assumes an overage movement speed and schedules the departure time accordingly. "Realistic walking speed" drastically decreases the on-feet speed, so citizens probably arrive way too late.

However, the complaints are that the visitors leave the event before it ends. This cannot be caused by that mod. And this is what I could not reproduce at all.

**Comment by Sipke82** [comment] 2019-05-29 18:04
Perhaps "random" visitors were mistaken for "event" visitors. Which could lead to that conclusion...

Perhaps it's a good idea to check for realistic walking speed and adapt the schedules accordingly? As I can imagine that many real time users would combine with realistic walking speed.

**Comment by dymanoid** [comment] 2019-05-29 18:14
Created #218 for that.

**Comment by RenaKunisaki** [comment] 2019-05-30 17:59
I thought Realistic Walking Speed was incompatible (and redundant) with Real Time? I had been using it before but I turned it off when I started using Real Time.

**Comment by dymanoid** [comment] 2019-05-30 18:13
**Realistic Walking Speed** is compatible with **Real Time** and not really redundant, because both mods affect different things. However, they not always play well together (hence #218).

One more thing: if the weather is bad, citizens refuse to visit events. This is by design in **Real Time**. Maybe the weather was bad when there were few event visitors?

**Comment by Mazisky** [comment] 2019-09-22 01:48
I've reinstalled the mod recently and i've still the issue of people leaving events.

Now i'll try every combination trying to find what causes it.

**Comment by dymanoid** [comment] 2020-03-23 18:27
@Mazisky Any news on this?

**Comment by dymanoid** [comment] 2020-04-05 15:02
Closing due to no feedback. If the problem still exists, the issue can be reopened.

**Closed by dymanoid** 2020-04-05 15:02 UTC
Labels: cannot reproduce
