### ISSUE TITLE
Vehicles as part of a line also are dark in the night

### ISSUE THREAD

**Issue by CimAd** [dymanoid/RealTime#142] opened 2018-08-01 21:59 UTC
During night time, vehicles that are part of a line are dark, ie. busses and trams, and trains that are operating a line. But international trains (unassigned) have lights, as do cable cars. 

Passenger train stations are also dark, even if they are obviously in use.

**Comment by benzoll37** [comment] 2018-08-02 00:51
Curious, all these lights work for me.

**Comment by CimAd** [comment] 2018-08-02 05:02
I'll try run a few experiments. I do use Workshop Assets for my public transport vehicles, the train stations are standard game assets though.

**Comment by benzoll37** [comment] 2018-08-02 15:16
Maybe that's why. My buses, trams and station train are vanilla.
However I have workshop trains, and they are illuminated. Keep in mind that even vanilla goods train, if it goes backwards, has no lighting. 
If you have a workshop train that does not have 1 machine at each end, it may not light up when driving backwards.

**Comment by dymanoid** [comment] 2018-08-02 16:55
This issue cannot be caused by **Real Time** due to a simple fact: there is not a single line of code that somehow affects the vehicles.

I can imagine that custom Workshop public transport buildings switch the lights out at night. This is possible if those buildings have a wrong category. **Real Time** doesn't switch the lights off in the public transport buildings, whereas it does e.g. for parks. I've seen in the Workshop many car parking garages that are categorized like "parks" in-game. Maybe you have some train stations that are wrongly categorized too.

But anyway, that's not **Real Time**'s issue either.

So I'm closing this issue as out of scope.

**Closed by dymanoid** 2018-08-02 16:55 UTC
